development:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>

test:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>


production:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>

