development:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>
  from: "test@example.com"

test:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>
  from: "test@example.com"


production:
  google_apps:
    client_id: <%= ENV['GAPPS_ID'] %>
    secret: <%= ENV['GAPPS_SECRET'] %>
    domain: <%= ENV['GAPPS_DOMAIN'] %>
  from: <%= ENV['POSTMARK_FROM'] %>
  postmark:
    api_key: <%= ENV['POSTMARK_API_KEY'] %>


